name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS and Pull Changes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MAIN_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASS }}
          script: |
            cd ~/seastudy-backend  # Adjust this path as needed
            git pull origin main
            go build -o seastudy

            # Kill any existing screen session named 'seastudy'
            screen -S seastudy -X quit || true

            # Start a new screen session and run the app
            screen -dmS seastudy ./seastudy
